### ISSUE TITLE
Show the number of items in the label of "Add all" button

### ISSUE THREAD

**Issue by pieterlukasse** [thehyve/react-select-checked#13]
Can we please show the current number of visible items in the drop down? It would be nice to show it next to "Add all". So the label would read "Add all (10)" if there are 10 visible items.

**Comment by rnugraha** [comment]
Nice idea. I would propose to  selected/total-options 

![schermafbeelding_2018-02-09_om_11_41_29](https://user-images.githubusercontent.com/2835281/36024202-506f8336-0d8f-11e8-9d1b-3af517c95012.png)

PS: Don't mind the yellow colouring.

**Comment by pieterlukasse** [comment]
hm...I think this will be confusing. Would "Add all (2/30)"  add 2 or 30 items in this case? I prefer just a single number, like "Add all (30)"

**Comment by fedde-s** [comment]
That does raise the question of whether that's the number of items that would be added to the current selection, the number of currently visible items that will be selected after clicking (including ones already selected), or the total number of items that will be selected in the end. To me, the last one seems the wrongest.

**Comment by rnugraha** [comment]
Good point. One thing still can be potentially confusing to the user is when you add all we actually only add **all visible** options. But this can be thought again later.
