### ISSUE TITLE
Typing backspace into search deselects selected option

### ISSUE THREAD

**Issue by adamabeshouse** [thehyve/react-select-checked#17]
Reproduce: 
(1) Select an option
(2) You'll notice that the search bar stops showing the placeholder
(3) Click into the search bar and hit the backspace key
(4) The option becomes deselected

**Comment by fedde-s** [comment]
#18 should have fixed the backspace issue, and I'm addressing the placeholder issue in #19.

**Comment by adamabeshouse** [comment]
thanks @fedde-s . I didn't realize that was a prop to react-select, the functionality was so counter intuitive to me that I just assumed it was a bug :)

**Comment by fedde-s** [comment]
In a way it was—I mostly see this component as a specialisation of `react-select` that adds some extra widgets based on the props it's passing down, and sets some configuration that makes sense next to those widgets. That's why it hardly has any instance state of itself.
