### ISSUE TITLE
Should behave as reactive, controlled component

### ISSUE THREAD

**Issue by adamabeshouse** [thehyve/react-select-checked#2]
Some features which are crucial for our use at cBioPortal which are present in the original React-Select are:

(1) Pass in as a prop the specification of which options are checked - the component should read this state from the prop, as opposed to having the component maintain this state internally.

This avoids a source of annoying UI bugs (one of the main ones that React is useful for avoiding) which is to be declarative about state and separate it from the internal logic of the component as much as possible, so that we dont have to duplicate state in different places in the application.

(2) Options should be able to change after initialization, reacting to the changed value of the options prop.

**Comment by pieterlukasse** [comment]
@adamabeshouse the example from README.md below fulfills (1), right? 
```javascript
var CheckedSelect = require('react-select-checked');

var options = [
  { value: 'one', label: 'One' },
  { value: 'two', label: 'Two' }
];

function logChange(val) {
  console.log('Selected: ', val);
}

<CheckedSelect
  name="form-field-name"
  value="one"
  options={options}
  onChange={logChange}
/>
```

**Comment by adamabeshouse** [comment]
@pieterlukasse based on what @rnugraha told me, that would just specify the initial state, whereas I think it's better for the state to always be read from that prop not just on initialization.

**Comment by rnugraha** [comment]
@adamabeshouse 
1) Initial value should be able to be set via attribute now
2) I exposed some async helpers from the original component. 

Could you have a look if these helps? Thanks

**Comment by adamabeshouse** [comment]
@rnugraha thanks for making adjustments. I think I didn't understand for some reason, but I think my requirement (2) was already met as you had it before. In any case, I think that should work now.

As far as (1), I think there has been some confusion - the desired functionality is to be able to specify, at all times, the selected state via prop - not just initially.

**Comment by pieterlukasse** [comment]
@rnugraha 
>" be able to specify, at all times, the selected state via prop - not just initially"  

-> this is now solved by setValue, right?

**Comment by rnugraha** [comment]
Hi @adamabeshouse, 

so like what @pieterlukasse said, for (1) you can set an initial value like:

```javascript
var CheckedSelect = require('react-select-checked');

var options = [
    {label: 'Chocolate', value: 'chocolate', disabled: true},
    {label: 'Vanilla', value: 'vanilla'},
    {label: 'Strawberry', value: 'strawberry'},
    {label: 'Caramel', value: 'caramel'},
];

var initialValue = [{label: 'Caramel', value: 'caramel'}];

function logChange(val) {
  console.log('Selected value: ', val);
}

<CheckedSelect
  name="form-field-name"
  value={initialValue}
  options={options}
  onChange={logChange}
/>
```
Code above will give the 'caramel' as the default selected value. Does this what you mean?

**Comment by adamabeshouse** [comment]
Hi @rnugraha, no I'd like to be able to set - at all times, not just initially - the value.
```
// Pseudocode
private selected;

private onClick(opt) {
    this.selected.toggle(opt);
}

render() {
    return <CheckedSelect value={this.selected} onClick={this.onClick}/>
}
```

**Comment by fedde-s** [comment]
I agree. As the current list of values is relevant to the parent component, it should not be internal state of the `Select` component. The `Select` component should just trust the parent's callback make sure it gets new value as a `prop` when re-rendering. This is how standard HTML input elements are usually handled in React components: https://reactjs.org/docs/forms.html#controlled-components

**Comment by fedde-s** [comment]
In other words, the state of the element that *uses* `CheckedSelect` in its render method should be the ‘source of truth’ for the currently selected (and not just initial) value, and it tells `CheckedSelect` what value to render with at any given time via the `value=` prop.

**Comment by fedde-s** [comment]
This design principle of React apps is explained in depth on this page: https://reactjs.org/docs/lifting-state-up.html

**Comment by rnugraha** [comment]
I think this should've already been supported. Pls look at the example and check if this is the expected behaviour: 

https://github.com/rnugraha/component-lib-playground/blob/test-react-select-checked/src/components/IceCreamFlavours.js

**Comment by fedde-s** [comment]
Pull request #3 should fix the remaining issues and make it behave as expected. Could you check, and if you agree, merge it in?

**Comment by fedde-s** [comment]
Thanks, @rnugraha!

@adamabeshouse, does that solve your issue?

**Comment by adamabeshouse** [comment]
:+1:
