### ISSUE TITLE
The next row should not be highlighted after selection

### ISSUE THREAD

**Issue by zhx828** [thehyve/react-select-checked#23]
Example: After selecting Cancer Type, the Caner Type Detailed row is highlighted.
![aug-30-2018 17-38-32](https://user-images.githubusercontent.com/5400599/44880872-b86e6e80-ac7b-11e8-9979-24344f78138e.gif)

**Comment by fedde-s** [comment]
Is this a duplicate of https://github.com/thehyve/react-select-checked/issues/7?

**Comment by zhx828** [comment]
Yeah seems like it. Closing
