### ISSUE TITLE
‘Add all’ deselects currently invisible options

### ISSUE THREAD

**Issue by fedde-s** [thehyve/react-select-checked#4]
If I:

1. select an option in the dropdown (say, ‘Peppermint’) and then
2. make it invisible, either by searching/filtering for prefixes not in my selection (say, ‘Co’ to match both ‘Cookies and Cream’ and ‘Coconut’) or by externally changing the `options=` prop, and I subsequently
3. press the **Add all** button,

then

4. this does not only cause the component to select all currently visible options, but also to deselect the now-invisible one.

I believe that this is *not* the intended behaviour, as the **Clear all** button only deselects visible values while leaving invisible ones untouched.

**Comment by fedde-s** [comment]
I proposed a fix for this in pull request #5.

**Comment by rnugraha** [comment]
#5 merged
