### ISSUE TITLE
Toggling an option clears filter text

### ISSUE THREAD

**Issue by fedde-s** [thehyve/react-select-checked#6]
When I type a few letters to filter the list of options, and then check or uncheck one of the options that are still visible, that also causes the letters I had typed to disappear and the dropdown list all options again. I'd expect the filter to be unaffected so that I could select another option from the filtered list.

**Comment by rnugraha** [comment]
Looks like a bug.

**Comment by fedde-s** [comment]
This behaviour also exists in the underlying [**react-select** component](https://jedwatson.github.io/react-select/#react-select-3--value), which was originally designed to have the menu close every time an option is selected. For their use-cases it may not be a bug, but in ours, combined with `closeOnSelect=false`, it might be pretty useful to be able to change this behaviour even if it isn't the default. We should try to get this enhancement implemented upstream.

**Comment by fedde-s** [comment]
I informed the upstream project of my idea for enhancement in issue JedWatson/react-select#2168.

**Comment by fedde-s** [comment]
In the upstream issue report, someone [pointed out](https://github.com/JedWatson/react-select/issues/2168#issuecomment-349912431) that the desired behaviour can be enabled by setting the prop `onSelectResetsInput={false}` on the Select component.
